# -*- coding: utf-8 -*-
"""GAMP - Graphical Analysis of Mapper Parameters - Version 1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzFVOjeAuZNNBOwXEMCsL8iLY5A_ZXEo

<h1><b>GAMP - Graphical Analysis of Mapper Parameters - Version 1.0</b></h1>

* GAMP is a computational pipeline designed to graphically analyze how different parameter choices influence the topological structure of the graphs generated by the Mapper algorithm.

* By automating the execution across a wide range of configurations, GAMP allows researchers to identify relevant topological insights through quantitative metrics and a combined multicriteria score.


<br><br><br>


---

# **1) Initial configuration**

* In this section, we upload the input, import the necessary libraries, and read the input file.

<br>

### **Upload the input file**

* Run the cell below and upload the file using the button shown in the cell output.

* The input to the pipeline must be a file in TSV format.

* After uploading the input datasets, run the next cells.
"""

from google.colab import files
uploaded_file = files.upload()
file_name = list(uploaded_file.keys())[0]

"""<br>

### **Import libraries**
"""

!pip install kmapper
import kmapper as km

import os
import warnings
import pandas as pd
import numpy as np
import seaborn as sns

import networkx as nx

import sklearn as sk
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from sklearn.mixture import BayesianGaussianMixture
from sklearn.cluster import AgglomerativeClustering
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.cm as cm
from matplotlib.colors import ListedColormap
from matplotlib.backends.backend_pdf import PdfPages

# Visual progress bar
from tqdm.notebook import tqdm

"""<br>

### **Initial settings**
"""

# Ignore all warnings
warnings.filterwarnings("ignore")

# Create the output folders
file_name_no_ext = os.path.splitext(file_name)[0]
output_folder = "Output/" + file_name_no_ext
os.makedirs(output_folder, exist_ok=True)

def print_title(title): print("\n", title, "\n", "="*len(title), sep="")

"""<br>

### **Read the input file**
"""

# Create dataframe from input
data_df = pd.read_csv(file_name, sep="\t")

data_df.head()

"""<br><br><br>

---

# **2) Data preprocessing**

<br>

### **Removing missing values**

* Remove rows from the dataframe that contain missing values ​​in one or more columns.
"""

print_title("Count of null values per column")
print(data_df.isnull().sum())

print_title("\nRemoving missing values")
original_rows = len(data_df)
data_df.dropna(inplace=True)

print(f"Number of original rows: {original_rows}")
print(f"Number of rows after removing NaNs: {len(data_df)}")
print(f"Result: {original_rows - len(data_df)} rows with null values were removed")

"""<br>

### **Handling categorical data**

* The Mapper algorithm require numeric input.

* If the DataFrame contains columns of type 'object', they are likely text/categorical and must be converted to numerical values.
"""

# Print dataframe information
print_title("DataFrame information")
data_df.info()

print("\n")
print_title("Handling categorical data")

# Select categorical columns from dataframe
categorical_cols = data_df.select_dtypes(include=['object']).columns

# Verify if the dataframe contains any categorical columns
if not categorical_cols.empty:
    print(f"Found categorical columns: {list(categorical_cols)}")
    data_df = pd.get_dummies(data_df, columns=categorical_cols, drop_first=True)
    print("Categorical columns have been converted to numeric")
    print("New DataFrame shape:", data_df.shape)
else:
    print("No categorical columns found.")

"""<br>

### **Data after preprocessing**

* Display dataframe data after data preprocessing.
"""

data_df.head()

"""<br><br><br>

---

# **3) Functions - Mapper**

  - In this section, functions related to the Mapper algorithm are implemented.

<br>

### **Functions - Metrics and scores calculations**

* Functions to calculate metrics and scores from a Mapper algorithm result.
"""

# Calculate connected components

def calc_connected_components(mapper_graph, num_clusters):
    num_connected_components = 0
    if num_clusters > 0:
        # Create a NetworkX graph from Mapper output
        G = nx.Graph()

        # Add nodes (clusters) to the graph
        G.add_nodes_from(mapper_graph["nodes"].keys())

        # Add the edges
        for source, targets in mapper_graph['links'].items():
            for target in targets:
                G.add_edge(source, target)

        # Calculate the number of connected components
        num_connected_components = nx.number_connected_components(G)

    return num_connected_components

"""<br>"""

# Calculate the number of unclustered samples

def calc_unclustered_samples(mapper_graph, total_samples, num_clusters):
    if num_clusters == 0:
        # Handle the case where no clusters are formed
        unclustered_samples = total_samples
    else:
        samples_in_clusters = set()
        for node_name in mapper_graph["nodes"]:
            member_indices = mapper_graph["nodes"][node_name]
            samples_in_clusters.update(member_indices)
        unclustered_samples = total_samples - len(samples_in_clusters)

    return unclustered_samples

"""<br>"""

# Calculate the score of a metric

def calc_score(current_value, range_dict):
    vmin = range_dict["vmin"]
    vmax = range_dict["vmax"]
    range_width = vmax - vmin

    if current_value < vmin:
        distance = vmin - current_value
    elif current_value > vmax:
        distance = current_value - vmax
    else:
        distance = 0

    if range_width == 0:
        score = 1.0 if distance == 0 else 0.0
    else:
        score = max(0.0, 1 - (distance / range_width))

    return score

"""<br>"""

# Calculate the combined score of a Mapper algorithm result

def calc_combined_score(score_params, unclustered_samples, num_clusters, num_edges,
                        num_connected_components, std_dev_cluster_sizes):

    score1 = calc_score(unclustered_samples, score_params["target_unclustered"])
    score2 = calc_score(num_clusters, score_params["target_clusters"])
    score3 = calc_score(num_edges, score_params["target_edges"])
    score4 = calc_score(num_connected_components, score_params["target_connected_components"])
    score5 = calc_score(std_dev_cluster_sizes, score_params["target_std_dev_cluster_sizes"])

    total_weights = sum(score_params[f"weight_score{i}"] for i in range(1, 6))

    combined_score = (score_params["weight_score1"] * score1 +
                      score_params["weight_score2"] * score2 +
                      score_params["weight_score3"] * score3 +
                      score_params["weight_score4"] * score4 +
                      score_params["weight_score5"] * score5 ) / total_weights
    combined_score = max(0, combined_score)

    return combined_score

"""<br>

### **Function - Format plot titles**

* This function formats the title of the plots.
"""

# Format the projection function title
def format_projection_title(proj_func):
    if isinstance(proj_func, PCA):
        projection_title = (f"Projection: PCA (n_components={proj_func.n_components})")
    elif isinstance(proj_func, TSNE):
        projection_title = (f"Projection: t-SNE (n_components={proj_func.n_components})")
    else:
        projection_title = (f"Projection: {proj_func}")

    return (projection_title)

# Format the clustering method title
def format_clustering_title(clust_alg):
    if isinstance(clust_alg, sk.cluster.DBSCAN):
        clustering_title = (f"Clustering: DBSCAN (eps={clust_alg.eps})")
    elif isinstance(clust_alg, sk.mixture.BayesianGaussianMixture):
        clustering_title = (f"Clustering: Bayesian Gaussian Mixture (n_components={clust_alg.n_components})")
    elif isinstance(clust_alg, sk.cluster.AgglomerativeClustering):
        clustering_title = (f"Clustering: Hierarchical Agglomerative Clustering (distance_threshold={clust_alg.distance_threshold})")
    else:
        clustering_title = (f"Clustering: {clust_alg}")

    return (clustering_title)

# Format the title with the projection function name and grouping method
def format_plot_title(proj_func, clust_alg):
    projection_title = format_projection_title(proj_func)
    clustering_title = format_clustering_title(clust_alg)
    return (projection_title + "\n\n" + clustering_title)

"""<br>

### **Function - Parameter analysis**

* Function that performs a parameter sweep for the Kepler Mapper algorithm.
"""

def run_mapper_analysis(mapper, normalized_data, projected_data, proj_func,
                        clust_alg, n_cubes_range, perc_overlap_range):
    results_data = []

    # Loop to run Mapper and collect metrics
    for n_cubes in n_cubes_range:
        for perc_overlap in perc_overlap_range:
            try:
                # Run the Mapper algorithm with the parameters of the current iteration
                cover = km.Cover(n_cubes=n_cubes, perc_overlap=perc_overlap)
                mapper_graph = mapper.map(lens=projected_data, X=normalized_data,
                              clusterer=clust_alg, cover=cover)

                # Calculate metrics
                num_clusters = len(mapper_graph["nodes"])
                num_edges = sum(len(v) for v in mapper_graph['links'].values())
                num_connected_components = calc_connected_components(mapper_graph, num_clusters)
                node_sizes = [len(members) for members in mapper_graph["nodes"].values()]
                std_dev_cluster_sizes = np.std(node_sizes) if num_clusters > 0 else 0.0
                unclustered_samples = calc_unclustered_samples(mapper_graph, total_samples, num_clusters)

                # Calculate the combined score of a Mapper algorithm result
                combined_score = calc_combined_score(score_params, unclustered_samples,
                                  num_clusters, num_edges, num_connected_components,
                                  std_dev_cluster_sizes)

                # Store the results
                results_data.append({
                  "projection_function": str(proj_func),
                  "clustering_algorithm": str(clust_alg),
                  "n_cubes": n_cubes,
                  "perc_overlap": perc_overlap,
                  "unclustered_samples": unclustered_samples,
                  "num_clusters": num_clusters,
                  "num_edges": num_edges,
                  "num_connected_components": num_connected_components,
                  "std_dev_cluster_sizes": std_dev_cluster_sizes,
                  "combined_score": combined_score
                })
            except ValueError as e:
                print(f"    Warning: Skipping combination for clusterer '{clust_alg}' with n_cubes={n_cubes}, perc_overlap={perc_overlap}. Reason: {e}")
                continue

    results_df = pd.DataFrame(results_data)
    return results_df

"""<br>

### **Function - Heatmaps of metrics**

* Function that generates heatmaps of metrics from the results of the Mapper algorithm.

* The heatmaps generated are for the following metrics:

  1. Number of unclustered samples

  2. Number of clusters

  3. Number of edges

  4. Number of connected components

  5. Standard deviation of cluster sizes

  6. Combined score
"""

def plot_heatmaps(results_df, pdf_pages, title=None):

    if results_df.empty:
        print("No results were generated. Skipping heatmap generation.")
        return

    # Create pivot tables for each metric, which is the expected format for heatmaps
    heatmap_unclustered = results_df.pivot(index="perc_overlap", columns="n_cubes", values="unclustered_samples")
    heatmap_num_clusters = results_df.pivot(index="perc_overlap", columns="n_cubes", values="num_clusters")
    heatmap_num_edges = results_df.pivot(index="perc_overlap", columns="n_cubes", values="num_edges")
    heatmap_std_dev_cluster_sizes = results_df.pivot(index="perc_overlap", columns="n_cubes", values="std_dev_cluster_sizes")
    heatmap_connected_components = results_df.pivot(index="perc_overlap", columns="n_cubes", values="num_connected_components")
    heatmap_combined_score = results_df.pivot(index="perc_overlap", columns="n_cubes", values="combined_score")

    fig, axes = plt.subplots(2, 3, figsize=(13, 8))
    axes = axes.flatten()
    fig.suptitle(title, fontsize=14)

    # Heatmap 1: Unclustered samples
    sns.heatmap(heatmap_unclustered, ax=axes[0], cmap="coolwarm", annot=True, fmt=".0f", linewidths=.5, vmin=0, vmax=30)
    axes[0].set_title("Unclustered samples")
    axes[0].set_xlabel("")
    axes[0].set_ylabel("perc_overlap")

    # Heatmap 2: Number of Clusters
    sns.heatmap(heatmap_num_clusters, ax=axes[1], cmap="viridis", annot=True, fmt=".0f", linewidths=.5, vmin=0, vmax=30)
    axes[1].set_title("Number of Clusters")
    axes[1].set_xlabel("")
    axes[1].set_ylabel("")

    # Heatmap 3: Number of Edges
    sns.heatmap(heatmap_num_edges, ax=axes[2], cmap="viridis", annot=True, fmt=".0f", linewidths=.5, vmin=0, vmax=40)
    axes[2].set_title("Number of Edges")
    axes[2].set_xlabel("")
    axes[2].set_ylabel("")

    # Heatmap 4: Connected components
    sns.heatmap(heatmap_connected_components, ax=axes[3], cmap="coolwarm", annot=True, fmt=".0f", linewidths=.5, vmin=0, vmax=5)
    axes[3].set_title("Connected Components")
    axes[3].set_xlabel("n_cubes (intervals)")
    axes[3].set_ylabel("perc_overlap")

    # Heatmap 5: Standard Deviation of Cluster Sizes
    sns.heatmap(heatmap_std_dev_cluster_sizes, ax=axes[4], cmap="viridis", annot=True, fmt=".1f", linewidths=.5, vmin=0.0, vmax=30)
    axes[4].set_title("Cluster Size Variation")
    axes[4].set_xlabel("n_cubes (intervals)")
    axes[4].set_ylabel("")

    # Heatmap 6: Combined Score
    sns.heatmap(heatmap_combined_score, ax=axes[5], cmap="coolwarm_r", annot=True, fmt=".2f", linewidths=.5, vmin=0.0, vmax=1)
    axes[5].set_title("Combined Score")
    axes[5].set_xlabel("n_cubes (intervals)")
    axes[5].set_ylabel("")

    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.subplots_adjust(hspace=0.5)
    plt.subplots_adjust(wspace=0.2)

    pdf_pages.savefig(fig, bbox_inches='tight')
    plt.close(fig)
    # plt.show()

"""<br>

### **Function - Boxplots of metrics**

* Function that generates boxplots to visualize the distribution of metrics from the results of the Mapper algorithm.
"""

def plot_boxplots(results_df, pdf_pages, title=None):

    if results_df.empty:
        print("No results were generated. Skipping boxplot generation.")
        return

    # List of metrics to be plotted
    metrics_to_plot = [
        "unclustered_samples",
        "num_clusters",
        "num_edges",
        "num_connected_components",
        "std_dev_cluster_sizes",
        "combined_score"
    ]

    # Titles for each subplot
    metric_titles = [
        "Distribution of Unclustered Samples",
        "Distribution of Number of Clusters",
        "Distribution of Number of Edges",
        "Distribution of Connected Components",
        "Distribution of Cluster Size Variation",
        "Distribution of Combined Score"
    ]

    fig, axes = plt.subplots(2, 3, figsize=(13, 8))
    axes = axes.flatten()
    fig.suptitle(title, fontsize=14)

    for i, metric in enumerate(metrics_to_plot):
        sns.boxplot(y=results_df[metric], ax=axes[i], width=0.4)
        axes[i].set_title(metric_titles[i], fontsize=10)
        axes[i].set_xlabel("")
        axes[i].set_ylabel("")

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.subplots_adjust(hspace=0.4)
    plt.subplots_adjust(wspace=0.4)

    pdf_pages.savefig(fig, bbox_inches='tight')
    plt.close(fig)

"""<br>

### **Function - Mapper graph**

* This function plots the static graph from the result of the Mapper algorithm.

  - The size of the node is proportional to its degree.

  - The color scale represents the number of samples in each cluster.
"""

import matplotlib.cm as cm
import matplotlib.colors as mcolors
import matplotlib.ticker as mticker

def plot_graph_mapper(mapper_graph, pdf_pages, nodes_spacing=None, title=None):
    # Convert the graph to NetworkX format
    nx_graph = km.adapter.to_nx(mapper_graph)

    # Create a dictionary for the numeric node labels (e.g. 'cube1_cluster0' -> '1')
    node_labels = {node_name: str(i+1) for i, node_name in enumerate(nx_graph.nodes())}

    # Calculate the number of samples in each node. This will define the node color.
    sample_counts = [len(mapper_graph["nodes"][node_name]) for node_name in nx_graph.nodes()]

    # Calculate the degree of each node. This will define the node size.
    degrees = [d for n, d in nx_graph.degree()]

    # Create a color list for each node based on its sample count
    cmap_samples = cm.get_cmap('plasma_r')
    min_sample_counts = min(sample_counts)
    max_sample_counts = max(sample_counts)
    if min_sample_counts == max_sample_counts:
        norm_samples = mcolors.Normalize(vmin=min_sample_counts, vmax=min_sample_counts + 1)
    else:
        norm_samples = mcolors.Normalize(vmin=min_sample_counts, vmax=max_sample_counts)
    node_colors_by_sample = cmap_samples(norm_samples(sample_counts))

    # Calculate the median of sample counts to use as a threshold
    median_value_samples = np.median(sample_counts)

    # Create a list of font colors: white for nodes with dark colors and black for the rest
    font_colors = []
    for color in node_colors_by_sample:
        luminance = (0.299 * color[0] + 0.587 * color[1] + 0.114 * color[2])
        font_colors.append('black' if luminance > 0.5 else 'white')

    # Create the figure and axes for the plot
    fig, ax = plt.subplots(figsize=(10, 8))

    # Define a layout for the graph to ensure consistent positioning
    # k: controls the distance between nodes. A larger value increases the spacing
    pos = nx.spring_layout(nx_graph, seed=42, k=nodes_spacing)

    # Draw the graph nodes
    nx.draw_networkx_nodes(nx_graph, pos, ax=ax,
                           node_color=node_colors_by_sample,
                           node_size=[300 + (d * 100) for d in degrees])

    # Draw the graph edges
    nx.draw_networkx_edges(nx_graph, pos, ax=ax)

    # Draw the node labels one by one to apply a specific font color to each
    for i, node_name in enumerate(nx_graph.nodes()):
        nx.draw_networkx_labels(nx_graph, pos, ax=ax,
                                labels={node_name: node_labels[node_name]},
                                font_color=font_colors[i], font_size=11, font_weight='bold')

    # Add color bar to chart
    sm = cm.ScalarMappable(cmap=cmap_samples, norm=norm_samples)
    sm.set_array([])
    cbar = plt.colorbar(sm, ax=ax, orientation='vertical', shrink=0.8, pad=0.05)
    cbar.set_label("Number of samples", rotation=90, labelpad=-58)

    # Set color bar ticks to integers
    if max_sample_counts > min_sample_counts:
        locator = mticker.MaxNLocator(nbins='auto', integer=True)
        cbar.ax.yaxis.set_major_locator(locator)

    # Final adjustments
    plt.title(title, fontsize=10)
    plt.tight_layout()
    plt.subplots_adjust(left=0.05, right=0.75, top=0.95, bottom=0.05)

    pdf_pages.savefig(fig, bbox_inches='tight')
    # plt.show()
    plt.close(fig)

"""<br>

### **Function - Result details**

* Function to print the details of the Mapper graphs for the top results in a TXT file.
"""

def print_result_details(output_file, mapper_graph, data_df, row, index ):

    # Convert the graph to NetworkX format
    nx_graph = km.adapter.to_nx(mapper_graph)

    # Create a dictionary for the numeric node labels (e.g. 'cube1_cluster0' -> '1')
    cluster_labels = {cluster_name: str(i+1) for i, cluster_name in enumerate(nx_graph.nodes())}

    # Create a list with the size of each node (number of samples)
    cluster_sizes = [len(mapper_graph["nodes"][cluster_name]) for cluster_name in nx_graph.nodes()]

    output_file.write("=" * 80 + "\n")
    output_file.write("Result #" + str(index+1) + "\n\n")

    output_file.write("Mapper algorithm parameters: \n")
    output_file.write("   Projection: " + str(row['projection_function']) + "\n" +
                      "   Clustering: " + str(row['clustering_algorithm']) + "\n" +
                      "   Intervals: " + str(row['n_cubes']) + "\n" +
                      "   Overlap: " + str(row['perc_overlap']) + "\n\n")

    output_file.write("Graph details: \n")
    output_file.write("   Number of clusters: " + str(row['num_clusters']) + "\n" +
                      "   Number of edges: " + str(row['num_edges']) + "\n" +
                      "   Connected components: " + str(row['num_connected_components'])  + "\n\n")

    output_file.write("Samples contained in each cluster:\n")

    # List of samples from all clusters
    all_cluster_samples = []

    # Print node information
    for cluster_name, cluster_label in cluster_labels.items():
        sample_indices = mapper_graph["nodes"][cluster_name]
        sample_names = data_df.index[sample_indices].tolist()
        all_cluster_samples.extend(sample_names)
        output_file.write(f"   Cluster {cluster_label} ({len(sample_names)} samples): {', '.join(map(str, sample_names))}\n")

    # Samples not in clusters
    unique_samples = list(set(all_cluster_samples))
    samples_not_in_clusters = set(data_df.index) - set(unique_samples)
    sorted_samples_not_in_clusters = sorted(list(samples_not_in_clusters))
    if len(sorted_samples_not_in_clusters) > 0:
        output_file.write(f"   Samples not found in clusters ({len(sorted_samples_not_in_clusters)} samples): {', '.join(map(str, sorted_samples_not_in_clusters))}\n\n\n")
    else:
        output_file.write(f"   Samples not found in clusters (0 samples)\n\n\n")

"""<br><br><br>

---

# **4) Parameter analysis**

* The Mapper algorithm is run with different parameters.

* Plots the results as heatmaps, boxplots, and graphs.

<br>

### **Parameters to be tested**

* Specify the projection functions, clustering methods, and parameters to run the Mapper algorithm.
"""

from sklearn.manifold import TSNE

# Define the parameter ranges to test
intervals_to_test = [5, 10, 15, 20, 30, 50]
perc_overlap_to_test = [0.1, 0.25, 0.5, 0.75]

# Define the fixed projection and clustering algorithms for the experiment
projections_to_test = [
    PCA(n_components=1, random_state=0),
    PCA(n_components=2, random_state=0),
    TSNE(n_components=1, random_state=0),
    TSNE(n_components=2, random_state=0),
]

clust_alg_to_test = [
    DBSCAN(eps=1.0),
    DBSCAN(eps=3.0),
    DBSCAN(eps=5.0),
    DBSCAN(eps=10.0),

    BayesianGaussianMixture(n_components=1, random_state=0),
    BayesianGaussianMixture(n_components=2, random_state=0),

    AgglomerativeClustering(n_clusters=None, distance_threshold=1.0),
    AgglomerativeClustering(n_clusters=None, distance_threshold=10.0),
    AgglomerativeClustering(n_clusters=None, distance_threshold=30.0),
    AgglomerativeClustering(n_clusters=None, distance_threshold=50.0)
]

"""<br>

### **Parameters of metrics and score**

* Specify the following parameters:

  - Range of target values ​​for the metrics.

  - Weight of each score in calculating the combined score.
"""

score_params = {
    # Target ranges [vmin, vmax]. A penalty is applied to the score only if the metric is outside this range.
    "target_unclustered": {"vmin": 0, "vmax": 0},
    "target_clusters": {"vmin": 10, "vmax": 12},
    "target_edges": {"vmin": 9, "vmax": 15},
    "target_connected_components": {"vmin": 1, "vmax": 1},
    "target_std_dev_cluster_sizes": {"vmin": 0, "vmax": 100},

    # Weight of each score in calculating the combined score
    "weight_score1": 0.3,
    "weight_score2": 0.2,
    "weight_score3": 0.2,
    "weight_score4": 0.3,
    "weight_score5": 0.0
}

"""<br>

### **Execution of the Mapper algorithm**

* Run the Mapper algorithm with the projection functions, clustering methods and parameters previously defined.

* Create a PDF file containing heatmaps of metrics from the results of the Mapper algorithm.
"""

# Calculate the number of samples in the input after preprocessing
total_samples = len(data_df)

# Get the total number of projection functions
total_proj_functions = len(projections_to_test)

# Paths to PDF files with graphs of metrics of all results of Mapper algorithm execution
output_pdf_heatmap_path = os.path.join(output_folder, f"All results - Heatmaps of metrics.pdf")
output_pdf_boxplot_path = os.path.join(output_folder, f"All results - Boxplots of metrics.pdf")

# List to store all results_df
all_results_list = []

# Create the multi-page PDF file using a context manager
with PdfPages(output_pdf_heatmap_path) as pdf_heatmaps, PdfPages(output_pdf_boxplot_path) as pdf_boxplots:
    for i, proj_func in enumerate(projections_to_test):
        print(f"\n\nStarting analysis with projection function [{i+1}/{total_proj_functions}]: {proj_func}")

        mapper = km.KeplerMapper(verbose=0)
        normalized_data = StandardScaler().fit_transform(data_df)
        projected_data = mapper.project(normalized_data, projection=proj_func)

        for clust_alg in tqdm(clust_alg_to_test, desc="    Progress"):
            # Perform analysis of the Mapper algorithm with different parameters
            results_df = run_mapper_analysis(mapper, normalized_data, projected_data, proj_func,
                                             clust_alg, intervals_to_test, perc_overlap_to_test)

            all_results_list.append(results_df)

            plot_title = format_plot_title(proj_func, clust_alg)
            plot_heatmaps(results_df, pdf_heatmaps, plot_title)
            plot_boxplots(results_df, pdf_boxplots, plot_title)

# Concatenate all DataFrames into a single one
all_results_df = pd.concat(all_results_list, ignore_index=True)

# Save the DataFrame with the metrics of all results as a TSV file
output_path = os.path.join(output_folder, "All results - Table of metrics.tsv")
all_results_df.to_csv(output_path, sep='\t', index=False)

print(f"\n\nComplete analysis successfully saved to: ")
print(f"   {output_pdf_heatmap_path}")
print(f"   {output_pdf_boxplot_path}")

"""<br>

### **Graphs of combined score distributions**

* Create a PDF file containing boxplots showing the distribution of the "combined score" of each clustering method to each projection function.

* Each page focuses on a single projection function, allowing you to compare the performance of the tested clustering algorithms for each projection function.
"""

print(f"\nStarting to generate graphs of performance comparison")

# Path to the PDF with the graphs
comparison_pdf_path = os.path.join(output_folder, f"All results - Distributions of combined scores.pdf")

# Get the list of unique projection functions that were tested
unique_projections = all_results_df['projection_function'].unique()

# Create the multi-page PDF file using a context manager
with PdfPages(comparison_pdf_path) as pdf:
    for i, proj_func_str in enumerate(unique_projections):
        print(f"   Creating plot for projection [{i+1}/{len(unique_projections)}]: {proj_func_str}")

        # Filter the main DataFrame to get results for the current projection only
        df_subset = all_results_df[all_results_df['projection_function'] == proj_func_str]

        fig, ax = plt.subplots(figsize=(14, 9))

        # Create the boxplot
        sns.boxplot(x='clustering_algorithm', y='combined_score', data=df_subset, ax=ax)

        title = format_projection_title(proj_func_str)
        ax.set_title(title, fontsize=16, pad=30)


        # Configure the axes
        ax.set_xlabel("")
        ax.set_ylabel("Combined Score", fontsize=12)
        ax.tick_params(axis='x', rotation=45, labelsize=10)
        plt.setp(ax.get_xticklabels(), ha="right", rotation_mode="anchor")

        plt.tight_layout()
        pdf.savefig(fig)
        # plt.show()
        plt.close(fig)


print(f"\nGraphs saved in: {comparison_pdf_path}")

"""<br>

### **Selection of the top results**

* Select the Mapper algorithm results that achieved the highest combined score.
"""

# Define the number of top results to view
N = 50

# Ensure we don't ask for more results than we have
N = min(N, len(all_results_df))

top_n_df = all_results_df.nlargest(N, 'combined_score').reset_index(drop=True)

# Save the DataFrame with the metrics of top results as a TSV file
output_path = os.path.join(output_folder, "Top results - Table of metrics.tsv")
top_n_df.to_csv(output_path, sep='\t', index=False)

top_n_df.head(5)

"""<br>

### **Graphs of the top results**

* Create a PDF file containing static graphs of the top results from the Mapper algorithm.
"""

# Reset mapper and normalize data
mapper = km.KeplerMapper(verbose=0)
normalized_data = StandardScaler().fit_transform(data_df)

# Path to the PDF file containing the Mapper graphs of the Top Results
output_pdf_mapper_graphs_path = os.path.join(output_folder, f"Top results - Mapper graphs.pdf")

# Path to the TXT file containing details about the Mapper graphs of the Top Results
output_txt_path = os.path.join(output_folder, f"Top results - Details of Mapper graphs.txt")

# Create the multi-page PDF file using a context manager
with PdfPages(output_pdf_mapper_graphs_path) as pdf_graphs, open(output_txt_path, 'w', encoding='utf-8') as output_file:
    print(f"\nStarting to generate graphs of the top results")
    output_file.write("Mapper graphs details of top results\n\n\n")

    for index, row in tqdm(top_n_df.iterrows(), total=len(top_n_df), desc="    Progress"):
        # Retrieve the result parameters to run the Mapper algorithm
        proj_str = row['projection_function']
        clust_str = row['clustering_algorithm']
        n_cubes = row['n_cubes']
        perc_overlap = row['perc_overlap']

        # Recreate the projection and clustering objects
        try:
            proj_func = eval(proj_str)
            clust_alg = eval(clust_str)
        except:
            print(f"  Warning: Could not recreate object for '{proj_func}' and '{clust_alg}'. Skipping execution of the Mapper algorithm.")
            continue

        # Run the Mapper algorithm with the parameters obtained from the top results
        projected_data = mapper.project(normalized_data, projection=proj_func)
        cover = km.Cover(n_cubes=n_cubes, perc_overlap=perc_overlap)
        mapper_graph = mapper.map(lens=projected_data, X=normalized_data,
                                  clusterer=clust_alg, cover=cover)

        # Plot the graph of the Mapper algorithm result in the PDF file
        plot_title = format_plot_title(proj_func, clust_alg)
        plot_title = plot_title + "\n\nIntervals: " + str(n_cubes) + " - Overlap: " + str(perc_overlap)
        plot_graph_mapper(mapper_graph, pdf_graphs, nodes_spacing=1.0, title=plot_title)

        # Prints Mapper graph details of the result in TXT file
        print_result_details(output_file, mapper_graph, data_df, row, index)


print(f"\nMapper graphs of top results saved in: {output_pdf_mapper_graphs_path}")
print(f"Mapper graphs details of top results saved in: {output_txt_path}")

"""<br><br><br>

---

# **5) Exporting results**

- This section allows the user to download the Output folder, which contains the generated plots, statistics, and any other result files produced during the analysis.

- The folder is first compressed into a .zip file, then a download button is displayed.

- By clicking the button, the zipped folder will be downloaded directly to the user’s computer.
"""

import shutil
import ipywidgets as widgets
from IPython.display import display
from google.colab import files

# Function to download the zip file
def on_download_button_clicked(b):
    files.download("Output.zip")

# Compact the Output folder
shutil.make_archive("Output", 'zip', "Output")

# Create download button
download_button = widgets.Button(description="Download Output", button_style='success')
download_button.on_click(on_download_button_clicked)
display(download_button)